/**
 * Emoji → Font Awesome icon mapping.
 * Maps common emoji/unicode pictographs to Font Awesome icon classes.
 */

export interface EmojiMapping {
  emoji: string;
  name: string;
  faClass: string;
  unicode: string;
}

// Emoji → FA mapping (curated top 100+)
const EMOJI_MAP: Record<string, Omit<EmojiMapping, "emoji">> = {
  "❤️": { name: "heart", faClass: "fa-heart", unicode: "\uf004" },
  "🔥": { name: "fire", faClass: "fa-fire", unicode: "\uf06d" },
  "⭐": { name: "star", faClass: "fa-star", unicode: "\uf005" },
  "✨": { name: "sparkles", faClass: "fa-star", unicode: "\uf005" },
  "⚡": { name: "zap", faClass: "fa-bolt", unicode: "\uf0e7" },
  "💎": { name: "gem", faClass: "fa-gem", unicode: "\uf3a5" },
  "👑": { name: "crown", faClass: "fa-crown", unicode: "\uf521" },
  "🏆": { name: "trophy", faClass: "fa-trophy", unicode: "\uf091" },
  "🎯": { name: "dart", faClass: "fa-bullseye", unicode: "\uf140" },
  "🚀": { name: "rocket", faClass: "fa-rocket", unicode: "\uf135" },
  "💡": { name: "bulb", faClass: "fa-lightbulb", unicode: "\uf0eb" },
  "🔑": { name: "key", faClass: "fa-key", unicode: "\uf084" },
  "🔒": { name: "lock", faClass: "fa-lock", unicode: "\uf023" },
  "🔗": { name: "link", faClass: "fa-link", unicode: "\uf0c1" },
  "📌": { name: "pin", faClass: "fa-thumbtack", unicode: "\uf08d" },
  "💰": { name: "money", faClass: "fa-sack-dollar", unicode: "\uf81d" },
  "📊": { name: "chart", faClass: "fa-chart-bar", unicode: "\uf080" },
  "📈": { name: "chart-up", faClass: "fa-chart-line", unicode: "\uf201" },
  "🎨": { name: "art", faClass: "fa-palette", unicode: "\uf53f" },
  "✏️": { name: "pencil", faClass: "fa-pencil", unicode: "\uf303" },
  "📝": { name: "memo", faClass: "fa-pen-to-square", unicode: "\uf044" },
  "📖": { name: "book", faClass: "fa-book", unicode: "\uf02d" },
  "💬": { name: "speech", faClass: "fa-comment", unicode: "\uf075" },
  "📢": { name: "megaphone", faClass: "fa-bullhorn", unicode: "\uf0a1" },
  "🔔": { name: "bell", faClass: "fa-bell", unicode: "\uf0f3" },
  "🎁": { name: "gift", faClass: "fa-gift", unicode: "\uf06b" },
  "🛒": { name: "cart", faClass: "fa-cart-shopping", unicode: "\uf07a" },
  "🏠": { name: "house", faClass: "fa-house", unicode: "\uf015" },
  "💻": { name: "laptop", faClass: "fa-laptop", unicode: "\uf109" },
  "📱": { name: "mobile", faClass: "fa-mobile", unicode: "\uf10b" },
  "⚙️": { name: "gear", faClass: "fa-gear", unicode: "\uf013" },
  "🔧": { name: "wrench", faClass: "fa-wrench", unicode: "\uf0ad" },
  "🔨": { name: "hammer", faClass: "fa-hammer", unicode: "\uf6e3" },
  "✅": { name: "check", faClass: "fa-circle-check", unicode: "\uf058" },
  "❌": { name: "cross", faClass: "fa-circle-xmark", unicode: "\uf057" },
  "⚠️": { name: "warning", faClass: "fa-triangle-exclamation", unicode: "\uf071" },
  "❗": { name: "exclamation", faClass: "fa-exclamation", unicode: "\uf12a" },
  "❓": { name: "question", faClass: "fa-question", unicode: "\uf128" },
  "💯": { name: "100", faClass: "fa-hundred-points", unicode: "\uf896" },
  "👍": { name: "thumbs-up", faClass: "fa-thumbs-up", unicode: "\uf164" },
  "👎": { name: "thumbs-down", faClass: "fa-thumbs-down", unicode: "\uf165" },
  "👏": { name: "clap", faClass: "fa-hands-clapping", unicode: "\uf817" },
  "🙏": { name: "pray", faClass: "fa-hands-praying", unicode: "\uf684" },
  "💪": { name: "muscle", faClass: "fa-hand-fist", unicode: "\uf6de" },
  "🤝": { name: "handshake", faClass: "fa-handshake", unicode: "\uf2b5" },
  "👆": { name: "point-up", faClass: "fa-hand-point-up", unicode: "\uf0a6" },
  "👇": { name: "point-down", faClass: "fa-hand-point-down", unicode: "\uf0a7" },
  "👉": { name: "point-right", faClass: "fa-hand-point-right", unicode: "\uf0a4" },
  "👈": { name: "point-left", faClass: "fa-hand-point-left", unicode: "\uf0a5" },
  "😀": { name: "grinning", faClass: "fa-face-smile", unicode: "\uf581" },
  "😂": { name: "joy", faClass: "fa-face-laugh-beam", unicode: "\uf59b" },
  "😍": { name: "heart-eyes", faClass: "fa-face-heart-eyes", unicode: "\uf7df" },
  "🤔": { name: "thinking", faClass: "fa-face-thinking", unicode: "\uf5c4" },
  "😎": { name: "cool", faClass: "fa-face-smile", unicode: "\uf581" },
  "😢": { name: "cry", faClass: "fa-face-sad-tear", unicode: "\uf5b4" },
  "😡": { name: "angry", faClass: "fa-face-angry", unicode: "\uf556" },
  "💀": { name: "skull", faClass: "fa-skull", unicode: "\uf54c" },
  "👻": { name: "ghost", faClass: "fa-ghost", unicode: "\uf6e2" },
  "🤖": { name: "robot", faClass: "fa-robot", unicode: "\uf544" },
  "🐶": { name: "dog", faClass: "fa-dog", unicode: "\uf6d3" },
  "🐱": { name: "cat", faClass: "fa-cat", unicode: "\uf6c0" },
  "🦊": { name: "fox", faClass: "fa-fox", unicode: "\uf813" },
  "🦁": { name: "lion", faClass: "fa-cat", unicode: "\uf6c0" },
  "🐸": { name: "frog", faClass: "fa-frog", unicode: "\uf6e8" },
  "🐝": { name: "bee", faClass: "fa-bug", unicode: "\uf188" },
  "🦋": { name: "butterfly", faClass: "fa-bug", unicode: "\uf188" },
  "🌸": { name: "blossom", faClass: "fa-seedling", unicode: "\uf4d8" },
  "🌺": { name: "hibiscus", faClass: "fa-seedling", unicode: "\uf4d8" },
  "🌹": { name: "rose", faClass: "fa-seedling", unicode: "\uf4d8" },
  "🌿": { name: "herb", faClass: "fa-leaf", unicode: "\uf06c" },
  "🍀": { name: "four-leaf", faClass: "fa-leaf", unicode: "\uf06c" },
  "🍁": { name: "maple", faClass: "fa-leaf", unicode: "\uf06c" },
  "🌴": { name: "palm", faClass: "fa-tree-palm", unicode: "\uf82b" },
  "🌳": { name: "tree", faClass: "fa-tree", unicode: "\uf1bb" },
  "🍎": { name: "apple", faClass: "fa-apple-whole", unicode: "\uf5d1" },
  "🍕": { name: "pizza", faClass: "fa-pizza-slice", unicode: "\uf818" },
  "🍔": { name: "burger", faClass: "fa-burger", unicode: "\uf805" },
  "☕": { name: "coffee", faClass: "fa-mug-hot", unicode: "\uf7b6" },
  "🍺": { name: "beer", faClass: "fa-beer-mug-empty", unicode: "\uf0fc" },
  "🍷": { name: "wine", faClass: "fa-wine-glass", unicode: "\uf4e3" },
  "⚽": { name: "soccer", faClass: "fa-futbol", unicode: "\uf1e3" },
  "🏀": { name: "basketball", faClass: "fa-basketball", unicode: "\uf434" },
  "🎮": { name: "gamepad", faClass: "fa-gamepad", unicode: "\uf11b" },
  "🎲": { name: "dice", faClass: "fa-dice", unicode: "\uf522" },
  "🎵": { name: "music", faClass: "fa-music", unicode: "\uf001" },
  "🎸": { name: "guitar", faClass: "fa-guitar", unicode: "\uf7a6" },
  "🎤": { name: "mic", faClass: "fa-microphone", unicode: "\uf130" },
  "🎧": { name: "headphones", faClass: "fa-headphones", unicode: "\uf025" },
  "🎬": { name: "clapper", faClass: "fa-clapperboard", unicode: "\uf846" },
  "✈️": { name: "airplane", faClass: "fa-plane", unicode: "\uf072" },
  "🚗": { name: "car", faClass: "fa-car", unicode: "\uf1b9" },
  "⛵": { name: "sailboat", faClass: "fa-sailboat", unicode: "\uf844" },
  "⚓": { name: "anchor", faClass: "fa-anchor", unicode: "\uf13d" },
  "🌍": { name: "globe", faClass: "fa-globe", unicode: "\uf0ac" },
  "☀️": { name: "sun", faClass: "fa-sun", unicode: "\uf185" },
  "🌙": { name: "moon", faClass: "fa-moon", unicode: "\uf186" },
  "🌈": { name: "rainbow", faClass: "fa-rainbow", unicode: "\uf8bc" },
  "❄️": { name: "snowflake", faClass: "fa-snowflake", unicode: "\uf2dc" },
  "🌊": { name: "wave", faClass: "fa-water", unicode: "\uf773" },
  "💧": { name: "droplet", faClass: "fa-droplet", unicode: "\uf043" },
  "🔮": { name: "crystal", faClass: "fa-circle", unicode: "\uf111" },
  "♻️": { name: "recycle", faClass: "fa-recycle", unicode: "\uf1b8" },
  "🚩": { name: "flag", faClass: "fa-flag", unicode: "\uf024" },
  "🎉": { name: "party", faClass: "fa-party-horn", unicode: "\uf880" },
  "🎊": { name: "confetti", faClass: "fa-party-horn", unicode: "\uf880" },
  "🎀": { name: "ribbon", faClass: "fa-ribbon", unicode: "\uf837" },
  "🔴": { name: "red-circle", faClass: "fa-circle", unicode: "\uf111" },
  "🟢": { name: "green-circle", faClass: "fa-circle", unicode: "\uf111" },
  "🔵": { name: "blue-circle", faClass: "fa-circle", unicode: "\uf111" },
  "⭐": { name: "star2", faClass: "fa-star", unicode: "\uf005" },
  "🌟": { name: "glowing-star", faClass: "fa-star", unicode: "\uf005" },
  "💫": { name: "dizzy", faClass: "fa-star", unicode: "\uf005" },
  "💥": { name: "boom", faClass: "fa-explosion", unicode: "\uf666" },
  "💢": { name: "anger", faClass: "fa-burst", unicode: "\uf633" },
  "💤": { name: "zzz", faClass: "fa-zzz", unicode: "\uf880" },
  "👁️": { name: "eye", faClass: "fa-eye", unicode: "\uf06e" },
  "🧠": { name: "brain", faClass: "fa-brain", unicode: "\uf5dc" },
  "🧸": { name: "teddy", faClass: "fa-bear", unicode: "\uf812" },
  "🧩": { name: "puzzle", faClass: "fa-puzzle-piece", unicode: "\uf12e" },
  "🎭": { name: "theater", faClass: "fa-masks-theater", unicode: "\uf630" },
  "📅": { name: "calendar", faClass: "fa-calendar", unicode: "\uf133" },
  "✉️": { name: "envelope", faClass: "fa-envelope", unicode: "\uf0e0" },
  "📞": { name: "phone", faClass: "fa-phone", unicode: "\uf095" },
  "🔌": { name: "plug", faClass: "fa-plug", unicode: "\uf1e6" },
  "🔋": { name: "battery", faClass: "fa-battery-full", unicode: "\uf240" },
  "📷": { name: "camera", faClass: "fa-camera", unicode: "\uf030" },
  "💾": { name: "floppy", faClass: "fa-floppy-disk", unicode: "\uf0c7" },
  "🖨️": { name: "printer", faClass: "fa-print", unicode: "\uf02f" },
  "🏷️": { name: "tag", faClass: "fa-tag", unicode: "\uf02b" },
  "📦": { name: "package", faClass: "fa-box", unicode: "\uf466" },
  "🗂️": { name: "folder", faClass: "fa-folder", unicode: "\uf07b" },
  "🔒": { name: "lock2", faClass: "fa-lock", unicode: "\uf023" },
  "🔓": { name: "unlock", faClass: "fa-lock-open", unicode: "\uf3c1" },
  "🛡️": { name: "shield", faClass: "fa-shield", unicode: "\uf132" },
  "⚔️": { name: "swords", faClass: "fa-swords", unicode: "\uf71d" },
  "🏹": { name: "archery", faClass: "fa-bullseye", unicode: "\uf140" },
  "⚖️": { name: "scales", faClass: "fa-scale-balanced", unicode: "\uf24e" },
  "🔮": { name: "crystal-ball", faClass: "fa-circle", unicode: "\uf111" },
  "🧲": { name: "magnet", faClass: "fa-magnet", unicode: "\uf076" },
  "💎": { name: "diamond", faClass: "fa-gem", unicode: "\uf3a5" },
  "🏅": { name: "medal", faClass: "fa-medal", unicode: "\uf5a2" },
  "🥇": { name: "gold", faClass: "fa-medal", unicode: "\uf5a2" },
  "🎗️": { name: "reminder", faClass: "fa-ribbon", unicode: "\uf837" },
  "🕯️": { name: "candle", faClass: "fa-lightbulb", unicode: "\uf0eb" },
  "💡": { name: "idea", faClass: "fa-lightbulb", unicode: "\uf0eb" },
  "🔔": { name: "notification", faClass: "fa-bell", unicode: "\uf0f3" },
  "📣": { name: "megaphone2", faClass: "fa-bullhorn", unicode: "\uf0a1" },
  "💬": { name: "comment", faClass: "fa-comment", unicode: "\uf075" },
  "🗣️": { name: "speaking", faClass: "fa-comment", unicode: "\uf075" },
  "👁️‍🗨️": { name: "eye-speech", faClass: "fa-eye", unicode: "\uf06e" },
  "❤️": { name: "love", faClass: "fa-heart", unicode: "\uf004" },
  "💔": { name: "broken-heart", faClass: "fa-heart-crack", unicode: "\uf7a9" },
  "❣️": { name: "heart-exclaim", faClass: "fa-heart", unicode: "\uf004" },
  "💕": { name: "two-hearts", faClass: "fa-heart", unicode: "\uf004" },
  "💖": { name: "sparkling-heart", faClass: "fa-heart", unicode: "\uf004" },
  "💗": { name: "growing-heart", faClass: "fa-heart", unicode: "\uf004" },
  "💘": { name: "heart-arrow", faClass: "fa-heart", unicode: "\uf004" },
  "💝": { name: "heart-ribbon", faClass: "fa-heart", unicode: "\uf004" },
  "♥️": { name: "heart-suit", faClass: "fa-heart", unicode: "\uf004" },
  "👆": { name: "up", faClass: "fa-hand-point-up", unicode: "\uf0a6" },
  "👇": { name: "down", faClass: "fa-hand-point-down", unicode: "\uf0a7" },
  "👉": { name: "right", faClass: "fa-hand-point-right", unicode: "\uf0a4" },
  "👈": { name: "left", faClass: "fa-hand-point-left", unicode: "\uf0a5" },
  "☝️": { name: "index-up", faClass: "fa-hand-point-up", unicode: "\uf0a6" },
  "✌️": { name: "peace", faClass: "fa-hand-peace", unicode: "\uf25b" },
  "🤞": { name: "crossed-fingers", faClass: "fa-hand-scissors", unicode: "\uf257" },
  "🤟": { name: "love-you", faClass: "fa-hand-love", unicode: "\uf821" },
  "🤘": { name: "metal", faClass: "fa-hand-horns", unicode: "\uf81e" },
  "👋": { name: "wave2", faClass: "fa-hand", unicode: "\uf256" },
  "✋": { name: "raised-hand", faClass: "fa-hand", unicode: "\uf256" },
  "👌": { name: "ok", faClass: "fa-hand-point-up", unicode: "\uf0a6" },
  "✊": { name: "fist", faClass: "fa-fist-raised", unicode: "\uf6de" },
  "👊": { name: "punch", faClass: "fa-fist-raised", unicode: "\uf6de" },
  "🤛": { name: "left-fist", faClass: "fa-fist-raised", unicode: "\uf6de" },
  "🤜": { name: "right-fist", faClass: "fa-fist-raised", unicode: "\uf6de" },
  "👐": { name: "open-hands", faClass: "fa-hands", unicode: "\uf255" },
  "🤲": { name: "palms-up", faClass: "fa-hands", unicode: "\uf255" },
  "🙌": { name: "raised-hands", faClass: "fa-hands", unicode: "\uf255" },
  "🖖": { name: "vulcan", faClass: "fa-hand-spock", unicode: "\uf259" },
  "💅": { name: "nail-polish", faClass: "fa-hand", unicode: "\uf256" },
  "🤳": { name: "selfie", faClass: "fa-mobile", unicode: "\uf10b" },
  "💪": { name: "bicep", faClass: "fa-hand-fist", unicode: "\uf6de" },
  "🦾": { name: "mechanical-arm", faClass: "fa-hand-fist", unicode: "\uf6de" },
  "🦿": { name: "mechanical-leg", faClass: "fa-shoe-prints", unicode: "\uf54b" },
  "🦵": { name: "leg", faClass: "fa-shoe-prints", unicode: "\uf54b" },
  "🦶": { name: "foot", faClass: "fa-shoe-prints", unicode: "\uf54b" },
  "👂": { name: "ear", faClass: "fa-ear", unicode: "\uf5f0" },
  "👃": { name: "nose", faClass: "fa-nose", unicode: "\uf881" },
  "👄": { name: "mouth", faClass: "fa-lips", unicode: "\uf882" },
  "🦷": { name: "tooth", faClass: "fa-tooth", unicode: "\uf5c9" },
  "👅": { name: "tongue", faClass: "fa-lips", unicode: "\uf882" },
  "👶": { name: "baby", faClass: "fa-baby", unicode: "\uf77c" },
  "🧒": { name: "child", faClass: "fa-child", unicode: "\uf1ae" },
  "👦": { name: "boy", faClass: "fa-child", unicode: "\uf1ae" },
  "👧": { name: "girl", faClass: "fa-child", unicode: "\uf1ae" },
  "🧑": { name: "person", faClass: "fa-person", unicode: "\uf183" },
  "👱": { name: "blonde", faClass: "fa-person", unicode: "\uf183" },
  "👨": { name: "man", faClass: "fa-person", unicode: "\uf183" },
  "🧔": { name: "bearded", faClass: "fa-person", unicode: "\uf183" },
  "👩": { name: "woman", faClass: "fa-person-dress", unicode: "\uf182" },
  "🧓": { name: "older", faClass: "fa-person", unicode: "\uf183" },
  "👴": { name: "old-man", faClass: "fa-person", unicode: "\uf183" },
  "👵": { name: "old-woman", faClass: "fa-person-dress", unicode: "\uf182" },
  "🙍": { name: "frowning", faClass: "fa-face-frown", unicode: "\uf119" },
  "🙎": { name: "pouting", faClass: "fa-face-angry", unicode: "\uf556" },
  "🙅": { name: "no-good", faClass: "fa-face-angry", unicode: "\uf556" },
  "🙆": { name: "ok-person", faClass: "fa-face-smile", unicode: "\uf581" },
  "💁": { name: "tipping", faClass: "fa-hand", unicode: "\uf256" },
  "🙋": { name: "raising", faClass: "fa-hand", unicode: "\uf256" },
  "🧏": { name: "deaf", faClass: "fa-ear-deaf", unicode: "\uf5f1" },
  "🙇": { name: "bowing", faClass: "fa-person", unicode: "\uf183" },
  "🤦": { name: "facepalm", faClass: "fa-face-palm", unicode: "\uf814" },
  "🤷": { name: "shrug", faClass: "fa-face-shrug", unicode: "\uf815" },
  "🧑‍⚕️": { name: "health-worker", faClass: "fa-user-doctor", unicode: "\uf0f0" },
  "👨‍⚕️": { name: "man-doctor", faClass: "fa-user-doctor", unicode: "\uf0f0" },
  "👩‍⚕️": { name: "woman-doctor", faClass: "fa-user-doctor", unicode: "\uf0f0" },
  "🧑‍🎓": { name: "student", faClass: "fa-user-graduate", unicode: "\uf501" },
  "👨‍🎓": { name: "man-student", faClass: "fa-user-graduate", unicode: "\uf501" },
  "👩‍🎓": { name: "woman-student", faClass: "fa-user-graduate", unicode: "\uf501" },
  "🧑‍🏫": { name: "teacher", faClass: "fa-user", unicode: "\uf007" },
  "👨‍🏫": { name: "man-teacher", faClass: "fa-user", unicode: "\uf007" },
  "👩‍🏫": { name: "woman-teacher", faClass: "fa-user", unicode: "\uf007" },
  "🧑‍💻": { name: "technologist", faClass: "fa-user-gear", unicode: "\uf509" },
  "👨‍💻": { name: "man-technologist", faClass: "fa-user-gear", unicode: "\uf509" },
  "👩‍💻": { name: "woman-technologist", faClass: "fa-user-gear", unicode: "\uf509" },
  "🧑‍🔧": { name: "mechanic", faClass: "fa-user-gear", unicode: "\uf509" },
  "👨‍🔧": { name: "man-mechanic", faClass: "fa-user-gear", unicode: "\uf509" },
  "👩‍🔧": { name: "woman-mechanic", faClass: "fa-user-gear", unicode: "\uf509" },
  "🧑‍🎨": { name: "artist", faClass: "fa-user", unicode: "\uf007" },
  "👨‍🎨": { name: "man-artist", faClass: "fa-user", unicode: "\uf007" },
  "👩‍🎨": { name: "woman-artist", faClass: "fa-user", unicode: "\uf007" },
  "🧑‍🚀": { name: "astronaut", faClass: "fa-user-astronaut", unicode: "\uf4fb" },
  "👨‍🚀": { name: "man-astronaut", faClass: "fa-user-astronaut", unicode: "\uf4fb" },
  "👩‍🚀": { name: "woman-astronaut", faClass: "fa-user-astronaut", unicode: "\uf4fb" },
  "🧑‍🚒": { name: "firefighter", faClass: "fa-user", unicode: "\uf007" },
  "👨‍🚒": { name: "man-firefighter", faClass: "fa-user", unicode: "\uf007" },
  "👩‍🚒": { name: "woman-firefighter", faClass: "fa-user", unicode: "\uf007" },
  "👮": { name: "police-officer", faClass: "fa-user-police", unicode: "\uf822" },
  "🕵️": { name: "detective", faClass: "fa-user-secret", unicode: "\uf21b" },
  "💂": { name: "guard", faClass: "fa-user-shield", unicode: "\uf505" },
  "🥷": { name: "ninja", faClass: "fa-user-ninja", unicode: "\uf504" },
  "👷": { name: "construction", faClass: "fa-user-helmet-safety", unicode: "\uf82c" },
  "🫅": { name: "crown-person", faClass: "fa-user", unicode: "\uf007" },
  "🤴": { name: "prince", faClass: "fa-user", unicode: "\uf007" },
  "👸": { name: "princess", faClass: "fa-user-dress", unicode: "\uf182" },
  "👳": { name: "turban", faClass: "fa-user", unicode: "\uf007" },
  "👲": { name: "skullcap", faClass: "fa-user", unicode: "\uf007" },
  "🧕": { name: "headscarf", faClass: "fa-user-dress", unicode: "\uf182" },
  "🤵": { name: "tuxedo", faClass: "fa-user-tie", unicode: "\uf508" },
  "👰": { name: "veil", faClass: "fa-user-dress", unicode: "\uf182" },
  "🤰": { name: "pregnant", faClass: "fa-person-pregnant", unicode: "\uf824" },
  "🫃": { name: "pregnant-man", faClass: "fa-person-pregnant", unicode: "\uf824" },
  "🫄": { name: "pregnant-person", faClass: "fa-person-pregnant", unicode: "\uf824" },
  "🤱": { name: "breastfeeding", faClass: "fa-baby", unicode: "\uf77c" },
  "👼": { name: "angel-baby", faClass: "fa-user", unicode: "\uf007" },
  "🎅": { name: "santa", faClass: "fa-user", unicode: "\uf007" },
  "🤶": { name: "mrs-claus", faClass: "fa-user-dress", unicode: "\uf182" },
  "🦸": { name: "superhero", faClass: "fa-user", unicode: "\uf007" },
  "🦹": { name: "supervillain", faClass: "fa-user", unicode: "\uf007" },
  "🧙": { name: "mage", faClass: "fa-user", unicode: "\uf007" },
  "🧚": { name: "fairy", faClass: "fa-user-dress", unicode: "\uf182" },
  "🧛": { name: "vampire", faClass: "fa-user", unicode: "\uf007" },
  "🧜": { name: "merperson", faClass: "fa-user", unicode: "\uf007" },
  "🧝": { name: "elf", faClass: "fa-user", unicode: "\uf007" },
  "🧞": { name: "genie", faClass: "fa-user", unicode: "\uf007" },
  "🧟": { name: "zombie", faClass: "fa-user", unicode: "\uf007" },
  "🧌": { name: "troll", faClass: "fa-user", unicode: "\uf007" },
  "💆": { name: "massage", faClass: "fa-user", unicode: "\uf007" },
  "💇": { name: "haircut", faClass: "fa-user", unicode: "\uf007" },
  "🚶": { name: "walking", faClass: "fa-person-walking", unicode: "\uf554" },
  "🧍": { name: "standing", faClass: "fa-person", unicode: "\uf183" },
  "🧎": { name: "kneeling", faClass: "fa-person", unicode: "\uf183" },
  "🏃": { name: "running", faClass: "fa-person-running", unicode: "\uf70c" },
  "💃": { name: "dancing", faClass: "fa-person-dress", unicode: "\uf182" },
  "🕺": { name: "man-dancing", faClass: "fa-person", unicode: "\uf183" },
  "👯": { name: "bunny-ears", faClass: "fa-person-dress", unicode: "\uf182" },
  "🧖": { name: "steam-room", faClass: "fa-user", unicode: "\uf007" },
  "🧗": { name: "climbing", faClass: "fa-person-walking", unicode: "\uf554" },
  "🤺": { name: "fencing", faClass: "fa-person", unicode: "\uf183" },
  "🏇": { name: "horse-racing", faClass: "fa-horse", unicode: "\uf6f0" },
  "⛷️": { name: "skier", faClass: "fa-person-skiing", unicode: "\uf7c9" },
  "🏂": { name: "snowboarder", faClass: "fa-person-skiing", unicode: "\uf7c9" },
  "🏌️": { name: "golfing", faClass: "fa-person-golf", unicode: "\uf798" },
  "🏄": { name: "surfing", faClass: "fa-person-surfing", unicode: "\uf7cd" },
  "🚣": { name: "rowing", faClass: "fa-person-rowing", unicode: "\uf806" },
  "🏊": { name: "swimming", faClass: "fa-person-swimming", unicode: "\uf5c4" },
  "⛹️": { name: "bouncing", faClass: "fa-person", unicode: "\uf183" },
  "🏋️": { name: "lifting", faClass: "fa-person", unicode: "\uf183" },
  "🚴": { name: "biking", faClass: "fa-person-biking", unicode: "\uf84a" },
  "🚵": { name: "mountain-biking", faClass: "fa-person-biking", unicode: "\uf84a" },
  "🤸": { name: "cartwheeling", faClass: "fa-person", unicode: "\uf183" },
  "🤼": { name: "wrestling", faClass: "fa-person", unicode: "\uf183" },
  "🤽": { name: "water-polo", faClass: "fa-person-swimming", unicode: "\uf5c4" },
  "🤾": { name: "handball", faClass: "fa-person", unicode: "\uf183" },
  "🤹": { name: "juggling", faClass: "fa-person", unicode: "\uf183" },
  "🧘": { name: "lotus", faClass: "fa-person", unicode: "\uf183" },
  "🛀": { name: "bath", faClass: "fa-bath", unicode: "\uf2cd" },
  "🛌": { name: "sleeping", faClass: "fa-bed", unicode: "\uf236" },
  "🧑‍🤝‍🧑": { name: "holding-hands", faClass: "fa-people-arrows", unicode: "\uf839" },
  "👭": { name: "women-holding", faClass: "fa-people-arrows", unicode: "\uf839" },
  "👫": { name: "woman-man", faClass: "fa-people-arrows", unicode: "\uf839" },
  "👬": { name: "men-holding", faClass: "fa-people-arrows", unicode: "\uf839" },
  "💏": { name: "kiss2", faClass: "fa-heart", unicode: "\uf004" },
  "💑": { name: "couple-heart", faClass: "fa-heart", unicode: "\uf004" },
  "👪": { name: "family", faClass: "fa-people-group", unicode: "\uf841" },
  "👨‍👩‍👦": { name: "family2", faClass: "fa-people-group", unicode: "\uf841" },
  "👨‍👩‍👧": { name: "family3", faClass: "fa-people-group", unicode: "\uf841" },
  "👨‍👩‍👧‍👦": { name: "family4", faClass: "fa-people-group", unicode: "\uf841" },
  "👨‍👩‍👦‍👦": { name: "family5", faClass: "fa-people-group", unicode: "\uf841" },
  "👨‍👩‍👧‍👧": { name: "family6", faClass: "fa-people-group", unicode: "\uf841" },
  "👩‍👩‍👦": { name: "family7", faClass: "fa-people-group", unicode: "\uf841" },
  "👩‍👩‍👧": { name: "family8", faClass: "fa-people-group", unicode: "\uf841" },
  "👩‍👩‍👧‍👦": { name: "family9", faClass: "fa-people-group", unicode: "\uf841" },
  "👩‍👩‍👦‍👦": { name: "family10", faClass: "fa-people-group", unicode: "\uf841" },
  "👩‍👩‍👧‍👧": { name: "family11", faClass: "fa-people-group", unicode: "\uf841" },
  "👨‍👨‍👦": { name: "family12", faClass: "fa-people-group", unicode: "\uf841" },
  "👨‍👨‍👧": { name: "family13", faClass: "fa-people-group", unicode: "\uf841" },
  "👨‍👨‍👧‍👦": { name: "family14", faClass: "fa-people-group", unicode: "\uf841" },
  "👨‍👨‍👦‍👦": { name: "family15", faClass: "fa-people-group", unicode: "\uf841" },
  "👨‍👨‍👧‍👧": { name: "family16", faClass: "fa-people-group", unicode: "\uf841" },
  "👩‍👦": { name: "family17", faClass: "fa-people-group", unicode: "\uf841" },
  "👩‍👧": { name: "family18", faClass: "fa-people-group", unicode: "\uf841" },
  "👩‍👧‍👦": { name: "family19", faClass: "fa-people-group", unicode: "\uf841" },
  "👩‍👦‍👦": { name: "family20", faClass: "fa-people-group", unicode: "\uf841" },
  "👩‍👧‍👧": { name: "family21", faClass: "fa-people-group", unicode: "\uf841" },
  "👨‍👦": { name: "family22", faClass: "fa-people-group", unicode: "\uf841" },
  "👨‍👧": { name: "family23", faClass: "fa-people-group", unicode: "\uf841" },
  "👨‍👧‍👦": { name: "family24", faClass: "fa-people-group", unicode: "\uf841" },
  "👨‍👦‍👦": { name: "family25", faClass: "fa-people-group", unicode: "\uf841" },
  "👨‍👧‍👧": { name: "family26", faClass: "fa-people-group", unicode: "\uf841" },
  "🫀": { name: "anatomical-heart", faClass: "fa-heart", unicode: "\uf004" },
  "🫁": { name: "lungs", faClass: "fa-lungs", unicode: "\uf604" },
  "🩸": { name: "blood", faClass: "fa-droplet", unicode: "\uf043" },
  "🩹": { name: "bandage", faClass: "fa-bandage", unicode: "\uf462" },
  "🩺": { name: "stethoscope", faClass: "fa-stethoscope", unicode: "\uf4f9" },
  "🩻": { name: "x-ray", faClass: "fa-x-ray", unicode: "\uf883" },
  "🩼": { name: "crutch", faClass: "fa-crutch", unicode: "\uf7f1" },
  "🪑": { name: "chair", faClass: "fa-chair", unicode: "\uf6c0" },
  "🪠": { name: "plunger", faClass: "fa-toilet", unicode: "\uf7d8" },
  "🪤": { name: "mouse-trap", faClass: "fa-cat", unicode: "\uf6c0" },
  "🪒": { name: "razor", faClass: "fa-scissors", unicode: "\uf0c4" },
  "🪓": { name: "axe2", faClass: "fa-hammer", unicode: "\uf6e3" },
  "🪃": { name: "boomerang", faClass: "fa-circle", unicode: "\uf111" },
  "🪄": { name: "wand", faClass: "fa-wand-magic-sparkles", unicode: "\uf72a" },
  "🪅": { name: "pinata", faClass: "fa-party-horn", unicode: "\uf880" },
  "🪆": { name: "nesting-dolls", faClass: "fa-circle", unicode: "\uf111" },
  "🪡": { name: "sewing-needle", faClass: "fa-scissors", unicode: "\uf0c4" },
  "🪢": { name: "knot", faClass: "fa-circle", unicode: "\uf111" },
  "🪣": { name: "bucket", faClass: "fa-bucket", unicode: "\uf821" },
  "🪤": { name: "mouse-trap2", faClass: "fa-cat", unicode: "\uf6c0" },
  "🪥": { name: "toothbrush", faClass: "fa-tooth", unicode: "\uf5c9" },
  "🪦": { name: "headstone", faClass: "fa-monument", unicode: "\uf5ef" },
  "🪧": { name: "placard", faClass: "fa-sign-hanging", unicode: "\uf710" },
  "🪨": { name: "rock", faClass: "fa-circle", unicode: "\uf111" },
  "🪩": { name: "mirror-ball", faClass: "fa-circle", unicode: "\uf111" },
  "🪪": { name: "identification", faClass: "fa-id-card", unicode: "\uf2c2" },
  "🪫": { name: "low-battery", faClass: "fa-battery-empty", unicode: "\uf244" },
  "🪬": { name: "hamsa", faClass: "fa-hand", unicode: "\uf256" },
  "🪭": { name: "folding-hand-fan", faClass: "fa-fan", unicode: "\uf863" },
  "🪮": { name: "hair-pick", faClass: "fa-scissors", unicode: "\uf0c4" },
  "🪯": { name: "khanda", faClass: "fa-star", unicode: "\uf005" },
  "🪰": { name: "fly", faClass: "fa-bug", unicode: "\uf188" },
  "🪱": { name: "worm", faClass: "fa-worm", unicode: "\uf828" },
  "🪲": { name: "beetle", faClass: "fa-bug", unicode: "\uf188" },
  "🪳": { name: "cockroach", faClass: "fa-bug", unicode: "\uf188" },
  "🪴": { name: "potted-plant2", faClass: "fa-seedling", unicode: "\uf4d8" },
  "🪵": { name: "wood2", faClass: "fa-tree", unicode: "\uf1bb" },
  "🪶": { name: "feather", faClass: "fa-feather", unicode: "\uf52d" },
  "🪷": { name: "lotus-flower", faClass: "fa-seedling", unicode: "\uf4d8" },
  "🪸": { name: "coral", faClass: "fa-water", unicode: "\uf773" },
  "🪹": { name: "empty-nest", faClass: "fa-tree", unicode: "\uf1bb" },
  "🪺": { name: "nest-eggs", faClass: "fa-tree", unicode: "\uf1bb" },
  "🪼": { name: "jellyfish", faClass: "fa-water", unicode: "\uf773" },
  "🪾": { name: "moose", faClass: "fa-horse", unicode: "\uf6f0" },
  "🪿": { name: "donkey", faClass: "fa-horse", unicode: "\uf6f0" },
  "🫀": { name: "anatomical-heart2", faClass: "fa-heart", unicode: "\uf004" },
  "🫁": { name: "lungs2", faClass: "fa-lungs", unicode: "\uf604" },
  "🫂": { name: "people-hugging", faClass: "fa-people-arrows", unicode: "\uf839" },
  "🫃": { name: "pregnant-man2", faClass: "fa-person-pregnant", unicode: "\uf824" },
  "🫄": { name: "pregnant-person2", faClass: "fa-person-pregnant", unicode: "\uf824" },
  "🫅": { name: "person-crown", faClass: "fa-user", unicode: "\uf007" },
  "🫆": { name: "finger-heart", faClass: "fa-heart", unicode: "\uf004" },
  "🫇": { name: "sarcastic", faClass: "fa-face-smile", unicode: "\uf581" },
  "🫈": { name: "shaking-face", faClass: "fa-face-smile", unicode: "\uf581" },
  "🫉": { name: "moose2", faClass: "fa-horse", unicode: "\uf6f0" },
  "🫊": { name: "donkey2", faClass: "fa-horse", unicode: "\uf6f0" },
  "🫋": { name: "wing", faClass: "fa-dove", unicode: "\uf4ba" },
  "🫌": { name: "leaf2", faClass: "fa-leaf", unicode: "\uf06c" },
  "🫍": { name: "mushroom", faClass: "fa-seedling", unicode: "\uf4d8" },
  "🫎": { name: "hyacinth", faClass: "fa-seedling", unicode: "\uf4d8" },
  "🫏": { name: "jellyfish2", faClass: "fa-water", unicode: "\uf773" },
  "🫐": { name: "blueberries2", faClass: "fa-seedling", unicode: "\uf4d8" },
  "🫑": { name: "bell-pepper", faClass: "fa-seedling", unicode: "\uf4d8" },
  "🫒": { name: "olive", faClass: "fa-seedling", unicode: "\uf4d8" },
  "🫓": { name: "flatbread", faClass: "fa-bread-slice", unicode: "\uf7ec" },
  "🫔": { name: "tamale", faClass: "fa-bread-slice", unicode: "\uf7ec" },
  "🫕": { name: "fondue", faClass: "fa-cheese", unicode: "\uf7ef" },
  "🫖": { name: "teapot", faClass: "fa-mug-hot", unicode: "\uf7b6" },
  "🫗": { name: "pouring", faClass: "fa-glass-water", unicode: "\uf80b" },
  "🫘": { name: "beans", faClass: "fa-seedling", unicode: "\uf4d8" },
  "🫙": { name: "jar", faClass: "fa-box", unicode: "\uf466" },
  "🫚": { name: "ginger", faClass: "fa-seedling", unicode: "\uf4d8" },
  "🫛": { name: "pea-pod", faClass: "fa-seedling", unicode: "\uf4d8" },
  "🫜": { name: "comb", faClass: "fa-scissors", unicode: "\uf0c4" },
  "🫝": { name: "slide", faClass: "fa-child-reaching", unicode: "\uf823" },
  "🫞": { name: "hamsa2", faClass: "fa-hand", unicode: "\uf256" },
  "🫟": { name: "maracas", faClass: "fa-music", unicode: "\uf001" },
  "🫠": { name: "melting", faClass: "fa-face-smile", unicode: "\uf581" },
  "🫡": { name: "saluting", faClass: "fa-face-smile", unicode: "\uf581" },
  "🫢": { name: "peeking", faClass: "fa-face-smile", unicode: "\uf581" },
  "🫣": { name: "eye-covering", faClass: "fa-eye-slash", unicode: "\uf070" },
  "🫤": { name: "diagonal-mouth", faClass: "fa-face-smile", unicode: "\uf581" },
  "🫥": { name: "dotted-line", faClass: "fa-face-smile", unicode: "\uf581" },
  "🫦": { name: "biting-lip", faClass: "fa-lips", unicode: "\uf882" },
  "🫧": { name: "bubbles2", faClass: "fa-droplet", unicode: "\uf043" },
  "🫨": { name: "shaking", faClass: "fa-face-smile", unicode: "\uf581" },
  "🫩": { name: "face-spiral", faClass: "fa-face-smile", unicode: "\uf581" },
  "🫪": { name: "camel", faClass: "fa-horse", unicode: "\uf6f0" },
  "🫫": { name: "bison", faClass: "fa-horse", unicode: "\uf6f0" },
  "🫬": { name: "mammoth", faClass: "fa-horse", unicode: "\uf6f0" },
  "🫭": { name: "dodo", faClass: "fa-dove", unicode: "\uf4ba" },
  "🫮": { name: "beaver", faClass: "fa-paw", unicode: "\uf706" },
  "🫯": { name: "sloth", faClass: "fa-paw", unicode: "\uf706" },
  "🫰": { name: "otter", faClass: "fa-paw", unicode: "\uf706" },
  "🫱": { name: "orangutan", faClass: "fa-paw", unicode: "\uf706" },
  "🫲": { name: "skunk", faClass: "fa-paw", unicode: "\uf706" },
  "🫳": { name: "flamingo", faClass: "fa-dove", unicode: "\uf4ba" },
  "🫴": { name: "parrot", faClass: "fa-dove", unicode: "\uf4ba" },
  "🫵": { name: "seal", faClass: "fa-paw", unicode: "\uf706" },
  "🫶": { name: "guide-dog", faClass: "fa-dog", unicode: "\uf6d3" },
  "🫷": { name: "probing-cane", faClass: "fa-blind", unicode: "\uf29d" },
  "🫸": { name: "ear-hearing", faClass: "fa-ear", unicode: "\uf5f0" },
  "🫹": { name: "manual-wheelchair", faClass: "fa-wheelchair", unicode: "\uf193" },
  "🫺": { name: "motorized-wheelchair", faClass: "fa-wheelchair", unicode: "\uf193" },
  "🫻": { name: "mechanical-leg2", faClass: "fa-shoe-prints", unicode: "\uf54b" },
  "🫼": { name: "ice-skate2", faClass: "fa-person-skating", unicode: "\uf7c5" },
  "🫽": { name: "roller-skate2", faClass: "fa-person-skating", unicode: "\uf7c5" },
  "🫾": { name: "nesting-dolls2", faClass: "fa-circle", unicode: "\uf111" },
  "🫿": { name: "maracas2", faClass: "fa-music", unicode: "\uf001" },
};

/**
 * Extract all emoji from a text string.
 */
export function extractEmoji(text: string): string[] {
  const emojiRegex = /\p{Emoji_Presentation}|\p{Extended_Pictographic}/gu;
  const matches = text.match(emojiRegex);
  return matches ? [...new Set(matches)] : [];
}

/**
 * Remove all emoji from text.
 */
export function removeEmoji(text: string): string {
  return text
    .replace(/\p{Emoji_Presentation}/gu, "")
    .replace(/\p{Extended_Pictographic}/gu, "")
    .replace(/\uFE0F/g, "")
    .replace(/\u200D/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Map emoji to Font Awesome icon data.
 */
export function mapEmojiToFontAwesome(emoji: string): EmojiMapping | null {
  const mapping = EMOJI_MAP[emoji];
  if (!mapping) return null;
  return { emoji, ...mapping };
}

/**
 * Get all unique FA icons from a text's emoji.
 */
export function getFontAwesomeFromText(text: string): EmojiMapping[] {
  const emojiList = extractEmoji(text);
  return emojiList
    .map(mapEmojiToFontAwesome)
    .filter((m): m is EmojiMapping => m !== null);
}

/**
 * Generate SVG for a Font Awesome icon at given size.
 */
export function generateFAIconSvg(
  faClass: string,
  size: number = 24,
  color: string = "#000000",
  strokeWidth: number = 0
): string {
  // Use Font Awesome CDN for rendering
  const iconUrl = `https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/svgs/solid/${faClass.replace("fa-", "")}.svg`;
  return `<image href="${iconUrl}" width="${size}" height="${size}" fill="${color}" stroke="${color}" stroke-width="${strokeWidth}"/>`;
}

/**
 * Generate a repeating SVG pattern using Font Awesome icons.
 */
export function generatePatternSvg(
  icons: EmojiMapping[],
  patternSize: number = 60,
  iconSize: number = 24,
  color: string = "#ffffff",
  opacity: number = 0.15,
  fill: "solid" | "outline" = "solid"
): string {
  if (icons.length === 0) return "";

  const iconElements = icons
    .map((icon, i) => {
      const x = (i % 2 === 0 ? 10 : patternSize / 2 + 10);
      const y = (i < 2 ? 15 : patternSize / 2 + 15);
      const strokeAttr = fill === "outline"
        ? `stroke="${color}" stroke-width="1.5" fill="none"`
        : `fill="${color}"`;
      return `<text x="${x}" y="${y}" font-size="${iconSize}" ${strokeAttr} opacity="${opacity}" font-family="'Font Awesome 6 Free', 'Font Awesome 6 Pro'" font-weight="900">${icon.unicode}</text>`;
    })
    .join("\n    ");

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${patternSize}" height="${patternSize}" viewBox="0 0 ${patternSize} ${patternSize}">
    ${iconElements}
  </svg>`;
}

/**
 * Generate a pattern as a data URL for use in CSS background-image.
 */
export function generatePatternDataUrl(
  icons: EmojiMapping[],
  patternSize: number = 60,
  iconSize: number = 24,
  color: string = "#ffffff",
  opacity: number = 0.15,
  fill: "solid" | "outline" = "solid"
): string {
  const svg = generatePatternSvg(icons, patternSize, iconSize, color, opacity, fill);
  if (!svg) return "";
  return `data:image/svg+xml,${encodeURIComponent(svg)}`;
}
